services:
  database:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_USER: dev1
      MYSQL_PASSWORD: dev1
      MYSQL_ROOT_PASSWORD: sb;,k,jk
    ports:
      - "3307:3306"
    volumes:
      - ./Database/script.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: ./Backend/
    ports:
      - "8080:8080"
    depends_on:
      - database
  frontend:
    build: ./Frontend/
    ports:
    - "80:80"
  # proxy:
  #   image: nginx:alpine
  #   volumes:
  #   - ./Proxy/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #   - "80:80"