services:
  database:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_USER: dev1
      MYSQL_PASSWORD: dev1
      MYSQL_ROOT_PASSWORD: sb;,k,jk
      MYSQL_AUTH_USER: authuser
      MYSQL_AUTH_PASSWORD: VT4eTSRo
    ports:
      - "3307:3306"
    volumes:
      - ./Database/script.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 2s
      timeout: 2s
      retries: 20
  backend:
    build: ./Backend/
    environment:
      mysql_url: database
    depends_on:
      database:
        condition: service_healthy
  frontend:
    build: ./Frontend/
  proxy:
    image: nginx:alpine
    volumes:
      - ./Proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./Proxy/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - ./Proxy/privkey.pem:/etc/nginx/ssl/privkey.pem
      - ./Proxy/dhparam-2048.pem:/etc/nginx/ssl/dhparam-2048.pem
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
