-- MySQL Script generated by MySQL Workbench
-- Tue Sep 17 03:50:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema itbkk_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema itbkk_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `itbkk_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `itbkk_db` ;

-- -----------------------------------------------------
-- Table `itbkk_db`.`boards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itbkk_db`.`boards` (
  `boardId` VARCHAR(10) NOT NULL,
  `boardName` VARCHAR(120) NOT NULL,
  `created_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `owner_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`boardId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itbkk_db`.`statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itbkk_db`.`statuses` (
  `statusId` INT NOT NULL auto_increment,
  `statusName` VARCHAR(50) NOT NULL,
  `statusDescription` VARCHAR(200) NULL DEFAULT NULL,
  `statusColor` VARCHAR(45) NOT NULL DEFAULT 'ffffff',
  `boardId` VARCHAR(10) NOT NULL,
  `created_on` DATETIME NOT NULL,
  `updated_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`statusId`, `boardId`),
  UNIQUE INDEX `statusName_UNIQUE` (`statusName` ASC, `boardId` ASC) VISIBLE,
  INDEX `fk_statuses_boards1_idx` (`boardId` ASC) VISIBLE,
  CONSTRAINT `fk_statuses_boards1`
    FOREIGN KEY (`boardId`)
    REFERENCES `itbkk_db`.`boards` (`boardId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itbkk_db`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itbkk_db`.`tasks` (
  `taskId` INT NOT NULL auto_increment,
  `taskTitle` VARCHAR(100) NOT NULL,
  `taskDescription` VARCHAR(500) NULL,
  `taskAssignee` VARCHAR(30) NULL,
  `createdOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `boardId` VARCHAR(10) NOT NULL,
  `statusId` INT NOT NULL,
  PRIMARY KEY (`taskId`, `boardId`, `statusId`),
  INDEX `fk_tasks_boards1_idx` (`boardId` ASC) VISIBLE,
  UNIQUE INDEX `taskTitle_UNIQUE` (`taskTitle` ASC) VISIBLE,
  INDEX `fk_tasks_statuses1_idx` (`statusId` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_boards1`
    FOREIGN KEY (`boardId`)
    REFERENCES `itbkk_db`.`boards` (`boardId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_statuses1`
    FOREIGN KEY (`statusId`)
    REFERENCES `itbkk_db`.`statuses` (`statusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itbkk_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itbkk_db`.`users` (
  `oid` CHAR(36) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `created_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`oid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itbkk_db`.`shared_boards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itbkk_db`.`shared_boards` (
  `sharedId` INT NOT NULL auto_increment,
  `boardId` VARCHAR(10) NOT NULL,
  `ownerOid` CHAR(36) NOT NULL,
  PRIMARY KEY (`sharedId`, `boardId`, `ownerOid`),
  INDEX `fk_boards_has_users_store_users_store1_idx` (`ownerOid` ASC) VISIBLE,
  INDEX `fk_boards_has_users_store_boards1_idx` (`boardId` ASC) VISIBLE,
  CONSTRAINT `fk_boards_has_users_store_boards1`
    FOREIGN KEY (`boardId`)
    REFERENCES `itbkk_db`.`boards` (`boardId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boards_has_users_store_users_store1`
    FOREIGN KEY (`ownerOid`)
    REFERENCES `itbkk_db`.`users` (`oid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
